### ISSUE TITLE
Unarchiving of the job to the temporary folder was unsuccessful.

### ISSUE THREAD

**Issue by csmith17-chwy** [open-automation/switch-portals#10]
The following error message occurred:

> Unarchiving of the job to the temporary folder was unsuccessful.

Here is a screen shot of the error. This happened with version 3. The file most likely retried and was successful.

<img width="1279" alt="screen shot 2016-09-14 at 9 22 44 am" src="https://cloud.githubusercontent.com/assets/11652313/18513811/f9e834ca-7a5c-11e6-9fe3-0bd42418fb8a.png">

**Comment by dominickp** [comment]
After reviewing the code, I think this is working as intended. If it occurs again or becomes a problem, please re-open this issue.
