### ISSUE TITLE
error-massage for Outgoing_v3.sscript

### ISSUE THREAD

**Issue by rzegwaard** [open-automation/switch-portals#13]
Hi,
Outgoing_v3.sscript generates an error message every run (20 secs) saying:

"Error in line 105 of script : TypeError. Undefined member function 'getPath' for object 'undefined' of type: 'Undefined'"

Robert

**Comment by dominickp** [comment]
Sorry for the late reply -- just saw this now. Seems that its failing to create a dataset when restoring a file. You sent the job into this portal via a V2 or V3 portal, right?

If so, what OS are you using? Could you enable verbose debugging and post your log with debug messages enabled?

**Comment by rzegwaard** [comment]
Hi Dominick,

Because of the error i stopped using those portals.
So i can’t reproduce this error right now.

Yes indeed, i’m using v3.
On OSX 10.11

Met vriendelijke groet,
Robert Zegwaard | ICT & New Media

OCC dehoog branding your business • De Wetering 30 • Postbus 128, 4900 AC Oosterhout
T. 0162 476 500 • Direct 0162 476 581 • www.occ-dehoog.nlhttp://www.occ-dehoog.nl/

Op alle prijsopgaven, transacties en leveringen die worden verstrekt via dit bericht zijn de Leveringsvoorwaarden voor de Grafische Industrie van toepassing. Gedeponeerd op 13 januari 2011 onder nr. 8/2011 ter griffie van de Rechtbank te Amsterdam. Indien deze niet beschikbaar worden gesteld in dit bericht kunt u deze downloaden van onze website https://nl-nl.facebook.com/OCCdehoog www.occ-dehoog.nlhttp://www.occ-dehoog.nl/.

NL - De inhoud van dit bericht en de eventueel daarbij behorende bijlagen zijn persoonlijk gericht aan en derhalve uitsluitend bestemd voor de geadresseerde. Zij kunnen gegevens met betrekking tot een derde bevatten. De ontvanger die niet de geadresseerde is, noch bevoegd is dit bericht namens geadresseerde te ontvangen, wordt verzocht de afzender onmiddellijk op de hoogte te stellen van de ontvangst. Elk gebruik van de inhoud van dit bericht en/of van de daarbij behorende bijlagen door een ander dan de geadresseerde is onrechtmatig jegens afzender respectievelijk de hiervoor bedoelde derde.

EN - The contents of this message, as well as any enclosures, are addressed personally to, and thus solely intended for the addressee. They may contain information regarding a third party. A recipient who is neither the addressee, nor empowered to receive this message on behalf of the addressee, is kindly requested to immediately inform the sender of receipt. Any use of the contents of this message and/or of the enclosures by any other person than the addressee is illegal towards the sender and the aforementioned third party.

© 2015 OCC De Hoog B.V. Alle rechten voorbehouden / All rights reserved

Op 1 nov. 2016, om 18:19 heeft Dominick Peluso <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Sorry for the late reply -- just saw this now. Seems that its failing to create a dataset when restoring a file. You sent the job into this portal via a V2 or V3 portal, right?

If so, what OS are you using? Could you enable verbose debugging and post your log with debug messages enabled?

**Comment by dominickp** [comment]
If you could help me reproduce this error, it would be a huge help. 

Please locate your ScriptData folder. This can be found within your Switch backing files. If you turn on debug logging and turn on verbose debugging, you should see the path in the log when any portal is activated. If you go to that path in Finder, if you could find the ScriptData folder and the SwitchPortalsEther folder within it. If you could zip up that entire folder and send it to me, it would allow me to debug why this job has a dataset that cannot be restored.

**Comment by dominickp** [comment]
Also, I have an updated version of V3 on this branch: https://github.com/open-automation/switch-portals/tree/normalize-path

This version will bypass restoring datasets if they cannot be restored. That doesn't explain why your dataset couldn't be restored, but it will allow you to use portals in this case. Once I do some more testing, I'll merge this branch into master.

**Comment by dominickp** [comment]
This version has been merged back into V3. If you could try the latest V3 and let me know what the log says, that would be very helpful.

**Comment by rzegwaard** [comment]
Hi Dominick,

I’ll try this version and let you know the results.

Meanwhile i’ve created my own icons for this script.
These are more in style with the other switch-icons.
If you like them, you can use them…

[cid:59D294F7-FB94-4BA4-BE02-229DDD44C056@dehoog.local][cid:FA6ADEEE-7F7A-40DA-97B9-770FD736DFDF@dehoog.local]

**Comment by dominickp** [comment]
Hey man, I don't think those attachments came through. Could you go to this link and drag them into the comment box? https://github.com/open-automation/switch-portals/issues/13

**Comment by rzegwaard** [comment]
Here are the icons!
Hope you like them.

![portal_in](https://cloud.githubusercontent.com/assets/22191418/20007632/6815f672-a29d-11e6-8d71-64e012eeb3fd.png)
![portal_out](https://cloud.githubusercontent.com/assets/22191418/20007633/68187906-a29d-11e6-92d6-f4b63c3d02b9.png)

**Comment by dominickp** [comment]
I do like those. They are much easier to understand what they do. Do you have a psd or ai file you could share as well? :)

**Comment by rzegwaard** [comment]
Here's the psd-file.

[portal_icons.psd.zip](https://github.com/open-automation/switch-portals/files/571755/portal_icons.psd.zip)

**Comment by rzegwaard** [comment]
For so far the last commit seems to work good. 
I don't see any error-messages.

**Comment by dominickp** [comment]
Good to know. Thanks for following up.
