### ISSUE TITLE
Opaque metadata lost

### ISSUE THREAD

**Issue by rzegwaard** [open-automation/switch-portals#16]
Hi,

Seems that opaque metadata, i my case a pdf-preflightreport, gets lost when going through the portal.
Is this known behavior?

Robert

**Comment by dominickp** [comment]
Thanks for reporting this. This is a bug, related to this line of code https://github.com/open-automation/switch-portals/blob/master/Unpacked/Outgoing_v3/Outgoing_v3.js#L95

I'm trying to determine the dataset based on the filename of the backing file. The way I'm doing it, I'm taking the last 3 characters of the filename, so for an xml dataset (mydataset.xml) it returns "xml". In the case of opaque, it's returning "que" which it then tries to use to create a new dataset with that model type.

I'll work on instrumenting a fix. In the mean time, you can get around this by packing and unpacking before and after sending the job into the portals.

**Comment by dominickp** [comment]
This has been resolved in the updated V3 of Outgoing of the script in this repo. I'll submit an updated app soon, but it will take a few days to reach the app store.

**Comment by rzegwaard** [comment]
Thanks!
