### ISSUE TITLE
Error in line 338 of script : Error. Failed to remove directory structure:

### ISSUE THREAD

**Issue by ABONSEY** [open-automation/switch-portals#18]
Using Portals on a Mac Server works fine.
Currently migrating to Windows 2016 server and have a few issues.
When a flow is migrated across and the scripts try to run I get the error in line 338.I then installed the Portals app and tried again. This time I get the error 'Cannot process job because the required connection is not available'. I've checked to input and output setting and they match the working Mac server settings.
Any thoughts

**Comment by dominickp** [comment]
Hmm... Could you try deleting the app on the flow and adding a new one, the manually entering the app properties again and seeing if that fixes it? Sometimes when you update, apps/configurators can get corrupted.

**Comment by ABONSEY** [comment]
Tried that.

**Comment by ABONSEY** [comment]
already

**Comment by ABONSEY** [comment]
Shame because it's been rock solid on the Mac server.

**Comment by ABONSEY** [comment]
Do you fancy Teamviewing it?

**Comment by dominickp** [comment]
Before we get to that, can you try to copy your log when you process a job through portals and put it here? It would help if you made a simple flow with a portal in and out.

**Comment by ABONSEY** [comment]
Tried  creating a basic flow and the apps worked without re-installing them.
Found some additional portal points in the flow that were still using the old scripting method. After updating them the flow then worked correctly :)
Thanks for your help
