### ISSUE TITLE
Review job ticket for other fields

### ISSUE THREAD

**Issue by dominickp** [open-automation/switch-portals#7]
Email address and hierarchy are reportedly being lost between portals.

**Comment by Kompetence** [comment]
I can confirm that "email addresses" and "email body text" gets lost, while "job state" and "job priority" are preserved and so is "private data".

**Comment by dominickp** [comment]
This has been fixed in dd46c8f6fdf03982aa036b77673289a8e1606d64

**Comment by Kompetence** [comment]
I have tested and can confirm that it all works now :-)
